import styled from '@emotion/styled';
import EmailIcon from '../../assets/email.svg';
import { useEmailGeneratorStore } from '../../store/store';
import Loader from '../Loader/Loader';
import GeneratedMailTemplate from './GeneratedMailTemplate';
import StaticMailTemplate from './StaticMailTemplate';

const RightContent = ({ isLoading = false, }) => {

  const { generatedEmail } = useEmailGeneratorStore();

  // function to render contents
  const renderContent = () => {
    if (isLoading) {
      return (
        <LoadingDiv>
          <Loader />
          <p style={{ fontSize: '1.2rem', fontWeight: 500, color: 'var(--color-grey-label)' }}>Generating your email...</p>
        </LoadingDiv>
      )
    }

    // when user just logged in and haven't generate email yet
    else if (!isLoading && !generatedEmail) {
      return (
        <StyledDiv>
          <img src={EmailIcon} />
          <SampleDiv>
            <p style={{ margin: 0, fontSize: '1.3rem', fontWeight: 600, color: 'var(--color-primary-purple)' }}>
              See a Sample Email
            </p>
            <p style={{ margin: '0.7rem', fontSize: '0.9rem', fontWeight: 400, color: 'var(--color-grey-label)' }}>
              This is a preview of the format you'll get. Fill in the form to generate your own.
            </p>

            <StaticMailTemplate />
          </SampleDiv>
        </StyledDiv>
      )
    }

    // when email is generated by user (api response)
    else {
      return (<GeneratedMailTemplate />)
    }
  }

  return (
    <Container>
      {renderContent()}
    </Container>
  )
}

const Container = styled.div`
  margin: 1rem 1.5rem;
  border-radius: 0.6rem;
  padding: 1rem 1.5rem;
  box-shadow: rgba(99, 99, 99, 0.2) 0px 2px 8px 0px;
  background: #fff;
  min-height: calc(100vh - 150px);
`
const LoadingDiv = styled.div`
  height: calc(100vh - 150px);
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
`
const StyledDiv = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
`
const SampleDiv = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  margin-top: 1rem;
`

export default RightContent;
